[project]
name = "automation-tools"
version = "0.1.0"
description = "Un ensemble d'outils personnel pour automatiser des tâches"
authors = [{ name = "Raphael Lossec", email = "raphaelossec@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nbconvert>=7.16.6",
]
